# Make sure to check the documentation at http://goreleaser.com
project_name: ipfs

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
-
  main: ./cmd/ipfs
  env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    - -extldflags "-static"
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    # - 386
# archive:
#   replacements:
#     darwin: Darwin
#     linux: Linux
#     windows: Windows
#     386: i386
#     amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
